name: cpu-build

on:
  push:
    paths-ignore: 
      - 'README.md'
      - '.github/**' 
      - 'docs/**'
      - '*.yml'
    branches:
      - master
  pull_request:
    paths-ignore: 
      - 'README.md'
      - '.github/**'
      - 'docs/**'
      - '*.yml'      
    branches: 
      - master

jobs:
  ci:
    name: ${{ matrix.version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [
          geant4.10.07.p03,
          geant4.10.06.p03,
        ]

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get install libxerces-c-dev

      - name: Install Geant4
        run: |
          wget https://github.com/hahnjo/geant4-actions-binaries/releases/download/${{ matrix.version }}/${{ matrix.version }}-binaries.tar.gz
          tar xf ${{ matrix.version }}-binaries.tar.gz -C $HOME
        shell: bash
        
      - name: Build & Test Debug
        run: |
          source ~/Geant4/bin/geant4.sh
          cmake -E remove_directory build
          cmake -B build -S . -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTING=ON
          cmake --build build
          cd build && ctest -j2 --verbose --output-on-failure

      - name: Build & Test Release
        run: |
          source ~/Geant4/bin/geant4.sh
          cmake -E remove_directory build
          cmake -B build -S . -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=ON
          cmake --build build
          cd build && ctest -j2 --verbose --output-on-failure
